# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution GIF

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Generate Snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=#22242e
            
      # Commit and push the changes
      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          create_branch: true
          branch: output
          push_options: '--force'
          commit_message: ":snake: Updates Snake Contribution Animation"
          commit_user_name: imexotic
          commit_user_email: hubert.stoklosa23@gmail.com
